name: Build debian package

on:
  push:
    tags:
      - v*

  pull_request:
    paths:
      - 'debian/changelog'
      - 'etc/DependencyInstaller.sh'
      - 'docker/*'
      - '.github/workflows/github-actions-build-deb-package.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  builder:
    name: 'Build debian package'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: ['debian10', 'debian11', 'ubuntu20', 'ubuntu22', 'ubuntu2210']

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: true
      
      - name: Create docker image
        run: |
          ./etc/DockerHelper.sh create -target=dev -os=${{ matrix.os }}

      - name: Build package
        run: |
          set -ex
          docker run \
          -v `pwd`:/OpenROAD \
          openroad/${{ matrix.os }}-dev:latest \
          bash -c "set -ex
            cd OpenROAD
            debuild --preserve-env --preserve-envvar=PATH -B"
      
      - name: Rename artifact
        id: artifact
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          set -ex
          cd ..
          file=openroad_*
          artifact=$(echo $file | sed 's/\.\([^.]*\)$/-${{ matrix.os }}.\1/')
          mv $file $artifact
          echo "file=$artifact" >> $GITHUB_OUTPUT
      
      - name: Upload artifact
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: ${{ steps.artifact.outputs.file }}
      